SWIDEA_SITE/server/apps/posts/urls.py
from django.urls import path
from . import views


app_name='posts' #네임 스페이스


urlpatterns= [
    path("", views.i_list, name='list'),
    path("posts/create", views.i_create , name='create'),
    path("posts/<int:pk>/update", views.i_update , name='update'),
    path("posts/<int:pk>/delete", views.i_delete,name='delete'),
    path("posts/<int:pk>", views.i_detail,name='detail'),
    path("posts/tool", views.t_list, name='t_list'),
    path("posts/tool/create", views.t_create , name='t_create'),
    path("posts/tool/<int:pk>", views.t_detail,name='t_detail'),
    path("posts/tool/<int:pk>/delete", views.t_delete,name='t_delete'),
    path("posts/tool/<int:pk>/update", views.t_update , name='t_update'),
   
]

SWIDEA_SITE/server/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("server.apps.posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/server/apps/posts/models.py
from django.db import models
from django.utils import timezone


class ToolList(models.Model):
    name=models.CharField(max_length=64)
    kind=models.CharField(max_length=64)
    content = models.TextField()

class Post(models.Model):
    title=models.CharField(max_length=64)
    devtool= models.ForeignKey(ToolList, on_delete=models.CASCADE)
    image=models.ImageField(blank=True, upload_to='posts/%Y%m%d')
    content = models.TextField()
    interest=models.IntegerField(default=0)
    timestamp = models.DateTimeField(default=timezone.now) #만들어진 시간

SWIDEA_SITE/server/apps/posts/views.py
from django.shortcuts import render,redirect
from server.apps.posts.models import Post, ToolList
from django.http.request import HttpRequest

def i_list(request:HttpRequest,*args, **kwargs):
    
    sort_option = request.GET.get('sort')
    print(sort_option)
    if sort_option:
        if sort_option=='byname':
            post_list=Post.objects.order_by('title')
        elif sort_option=='register':
            post_list=Post.objects.order_by('timestamp')
        elif sort_option=='newest':
            post_list=Post.objects.order_by('-timestamp')
        # elif sort_option=="pick":
        #     여기는 나중에 구현 해볼게여..
    else:
        post_list=Post.objects.all()

    context={
        'post_list':post_list
        }        
    return render(request,"posts/i_list.html",context=context)


def i_detail(request:HttpRequest,pk,*args, **kwargs):
    post = Post.objects.get(id=pk)
    print(post)
    context={
        "post": post,
    }
    return render(request, "posts/i_detail.html", context=context)

def i_create(request):
    devtools = ToolList.objects.all()
    if request.method == "POST":
        devtool_id = request.POST["devtool"]        
        Post.objects.create(
            title=request.POST["title"],
            devtool=ToolList.objects.get(id=devtool_id),
            interest=request.POST["interest"],
            content=request.POST["content"],
            image=request.FILES["image"],
        )
        return redirect("/")
    context={
        "devtools": devtools,
    }
    return render(request, "posts/i_create.html",context=context)


def i_update(request:HttpRequest, pk, *args, **kwargs):
    post = Post.objects.get(id=pk)
    devtools = ToolList.objects.all()
    
    if request.method == "POST":
        devtool=request.GET.get("devtool.id")
        devtool_id = request.POST.get("devtool")
        post.title=request.POST["title"]
        post.devtool=ToolList.objects.get(id=devtool_id),
        post.interest=request.POST["interest"]
        post.content=request.POST["content"]
        if devtool_id:
            post.image=request.FILES.get("image")
        post.save()
        return redirect(f"/posts/{post.id}")
    context={
        "post":post,
        'devtools' : devtools,        
    }
    return render(request, "posts/i_update.html", context=context)

def i_delete(request:HttpRequest, pk, *args, **kwargs):
    if request.method == "POST":
        post = Post.objects.get(id=pk)
        post.delete()
    return redirect("/")

def t_list(request:HttpRequest,*args, **kwargs):
    tool_list=ToolList.objects.all()

    context={
        'tool_list':tool_list
        }        
    return render(request,"posts/t_list.html",context=context)

def t_detail(request:HttpRequest,pk,*args, **kwargs):
    tool= ToolList.objects.get(id=pk)
    context={
        "tool": tool,
    }
    return render(request, "posts/t_detail.html", context=context)

def t_delete(request:HttpRequest, pk, *args, **kwargs):
    if request.method == "POST":
        tool = ToolList.objects.get(id=pk)
        tool.delete()
    return redirect("/posts/tool")

def t_create(request):
    if request.method == "POST":
        ToolList.objects.create(
        name=request.POST["name"],
        kind=request.POST["kind"],
        content=request.POST["content"],
        )
        return redirect("/posts/tool")
    return render(request, "posts/t_create.html")

def t_update(request:HttpRequest, pk, *args, **kwargs):
    tool = ToolList.objects.get(id=pk)
    context={
        "tool":tool,
    }
    if request.method == "POST":
        tool.name=request.POST["name"]
        tool.kind=request.POST["kind"]
        tool.content=request.POST["content"]
        tool.save()
        return redirect(f"/posts/tool/{tool.id}")
    return render(request, "posts/t_update.html", context=context)

SWIDEA_SITE/server/apps/posts/templates/posts/i_create.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>아이디어 등록 페이지</title>
    <link rel="stylesheet" href="{% static 'css/create.css'%}" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header><!-- 네비게이션바 -->
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:list' %}">My SW Idae Manage</a>
                <a class="nav-link active text-black small" href="{%url 'posts:create' %}">아이디어 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:list' %}">아이디어 관리</a>
                <a class="nav-link active text-black small" href="{%url 'posts:t_create' %}">개발 툴 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:t_list' %}">개발 툴 관리</a>
            </div>
        </nav>
    </header>

    <div class="title-box">
        <h1 class="title">Idea Register</h1>
        아이디어 등록 페이지 입니다. 당신의 아이디어를 잊지 말고 기록하세요!
    </div>

    <form action="{%url 'posts:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        아이디어 명:
        <input name="title" placeholder="아이디어 명" />
        <br />
        image:
        <input type="file" name="image" />
        <br />
        아이디어 설명:
        <textarea name="content" placeholder="게시글 내용"></textarea>
        <br />
        아이디어 관심도:
        <input name="interest" placeholder="interest" type="number" />
        <br />
        예상 개발 툴:
        <select name="devtool" id="devtool">
            <option value="" selected>-------</option>
            {% for devtool in devtools %}
            <option value="{{ devtool.id }}" name="devtool">{{ devtool.name }}</option>
            {% endfor %}
        </select>
        <div>
            <input type="submit" , value="SUBMIT" />
        </div>
    </form>
</body>

</html>

SWIDEA_SITE/server/apps/posts/templates/posts/i_detail.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>아이디어 상세 페이지 </title>
    <link rel="stylesheet" href="{% static 'css/detail.css'%}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header><!-- 네비게이션바 -->
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:list' %}">My SW Idae Manage</a>
                <a class="nav-link active text-black small" href="{%url 'posts:create' %}">아이디어 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:list' %}">아이디어 관리</a>
                <a class="nav-link active text-black small" href="{%url 'posts:t_create' %}">개발 툴 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:t_list' %}">개발 툴 관리</a>

            </div>
        </nav>
    </header>

    <div class="title-box">
        <h1 class="title">Idea Detail</h1>
        아이디어 세부 내용 페이지 입니다. 당신이 구현하려던 아이디어를 자세히 살펴보세요!
    </div>

    <div class="detail-box">
        {%if post.image %}
        <P>
            <img src="{{post.image.url}}">
        </P>
        {%endif%}
        <div class="text">
            <p>아이디어 관심도 : <br /> {{post.interest}}</p>
            <p>예상 개발 툴: <br />{{post.devtool.name}}</p>
            아이디어 설명:
            <p>{{post.content}}</p>

        </div>
    </div>

    <div class="button-box">
        <button>
            <a href="{% url 'posts:update' post.pk%}" style="color:black; text-decoration:none;">수정하기</a>
        </button>
        <button>
            <a href="{% url 'posts:list' %}" style="color:black; text-decoration:none;">목록</a>
        </button>
        <form action="{% url 'posts:delete' post.pk%}" method="post">
            {% csrf_token %}
            <input type="submit" , value="삭제하기" />
        </form>
    </div>
</body>

</html>

SWIDEA_SITE/server/apps/posts/templates/posts/i_list.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>아이디어 관리 페이지</title>
    <link rel="stylesheet" href="{% static 'css/list.css'%}" />
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header><!-- 네비게이션바 -->
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:list' %}">My SW Idae Manage</a>
                <a class="nav-link active text-black small" href="{%url 'posts:create' %}">아이디어 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:list' %}">아이디어 관리</a>
                <a class="nav-link active text-black small" href="{%url 'posts:t_create' %}">개발 툴 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:t_list' %}">개발 툴 관리</a>
            </div>
        </nav>
    </header>

    <div class="title-box">
        <h1 class="title">Idea List</h1>
        나의 아이디어를 잊지 말고 기록해 보세요
    </div>
    <form action="{% url 'posts:list' %}" method="get">
        <select name="sort" id="sort">
            <option value="none">=== 선택 ===</option>
            <option value="pick">찜하기순</option>
            <option value="byname">이름순</option>
            <option value="register">등록순</option>
            <option value="newest">최신순</option>
        </select>
    </form>

    <section class="idea-list">
        {% for post in post_list %}
        <article>
            <P>
                {%if post.image %}
                <img src="{{post.image.url}}">
                {%endif%}
            </P>
            <div>
                <p><a href="{% url 'posts:detail' post.pk%}">{{post.title}}</a></p>
                <div>예상개발 툴 : <a href="{% url 'posts:t_detail' post.devtool.id%}">{{post.devtool.name}}</a></div>
                <div>아이디어 관심도 : {{post.interest}}</div>
            </div>
        </article>
        <hr />
        {% endfor %}
    </section>
    <script type="text/javascript">
        $(document).ready(function () {
            $("select[name=sort]").change(function () {
                console.log(sort.value)
                $("form").submit();
                // location.reload();
                // $(".form").submit();
            });
        });
    </script>
</body>

</html>

SWIDEA_SITE/server/apps/posts/templates/posts/i_update.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>아이디어 수정 페이지</title>
    <link rel="stylesheet" href="{% static 'css/update.css'%}" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header><!-- 네비게이션바 -->
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:list' %}">My SW Idae Manage</a>
                <a class="nav-link active text-black small" href="{%url 'posts:create' %}">아이디어 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:list' %}">아이디어 관리</a>
                <a class="nav-link active text-black small" href="{%url 'posts:t_create' %}">개발 툴 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:t_list' %}">개발 툴 관리</a>
            </div>
        </nav>
    </header>

    <div class="title-box">
        <h1 class="title">Idea Detail Update</h1>
        아이디어 세부내용 수정 페이지입니다. 아이디어를 구체화 하거나 내용을 변경해 보세요.
    </div>

    <form action="{% url 'posts:update' post.pk%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        아이디어 명:
        <input name="title" placeholder="아이디어 명:" value="{{post.title}}" />
        <br />
        Image:
        {% if post.image %}
        <p>
            현재 이미지 : {{ post.image.url }}
        </p>
        <input type="file" name="image" />
        {% else %}
        <input type="file" name="image" />
        {% endif %}

        아이디어 설명:
        <textarea name="content" placeholder="게시글 내용">{{post.content}}</textarea>
        <br />
        아이디어 관심도:
        <input name="interest" placeholder="관심도" type="number" value="{{post.interest}}" />
        <br />
        예상 개발 툴:
        <select name="devtool" id="devtool">
            <option value="" selected>{{ post.devtool.name }}</option>
            {% for devtool in devtools %}
            {% if devtool.name != post.devtool.name %}
            <option value="{{ devtool.id }}" name="devtool">{{ devtool.name }}</option>
            {% endif %}
            {% endfor %}
        </select>
        <div>
            <input type="submit" , value="SUBMIT" />
        </div>
    </form>
</body>

</html>

SWIDEA_SITE/server/apps/posts/templates/posts/t_create.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>개발툴 등록 페이지</title>
    <link rel="stylesheet" href="{% static 'css/create.css'%}" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header><!-- 네비게이션바 -->
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:list' %}">My SW Idae Manage</a>
                <a class="nav-link active text-black small" href="{%url 'posts:create' %}">아이디어 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:list' %}">아이디어 관리</a>
                <a class="nav-link active text-black small" href="{%url 'posts:t_create' %}">개발 툴 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:t_list' %}">개발 툴 관리</a>
            </div>
        </nav>
    </header>

    <div class="title-box">
        <h1 class="title">DevTool Register</h1>
        개발툴 등록 페이지 입니다. 자신이 다룰 수 있는 개발툴을 등록해보세요.
    </div>

    <form action="{%url 'posts:t_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        이름:
        <input name="name" placeholder="이름" />
        <br />
        종류:
        <input name="kind" placeholder="종류" />
        <br />
        개발툴 설명:
        <textarea name="content" placeholder="개발툴 설명 내용"></textarea>
        <br />
        <div>
            <input type="submit" , value="SUBMIT" />
        </div>
    </form>
</body>

</html>

SWIDEA_SITE/server/apps/posts/templates/posts/t_detail.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>개발툴 상세 페이지 </title>
    <link rel="stylesheet" href="{% static 'css/t_detail.css'%}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header><!-- 네비게이션바 -->
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:list' %}">My SW Idae Manage</a>
                <a class="nav-link active text-black small" href="{%url 'posts:create' %}">아이디어 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:list' %}">아이디어 관리</a>
                <a class="nav-link active text-black small" href="{%url 'posts:t_create' %}">개발 툴 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:t_list' %}">개발 툴 관리</a>
            </div>
        </nav>
    </header>

    <div class="title-box">
        <h1 class="title">DevTool Detail</h1>
        개발툴 세부 내용 페이지 입니다. 자신이 다룰 수 있는 개발툴에 대한 상세 내용을 확인해보세요.
    </div>

    <div class="detail-box">
        <div class="text">
            <h1>{{tool.name}}</h1>
            <p>{{tool.kind}}</p>
            <p>{{tool.content}}</p>

        </div>
    </div>

    <div class="button-box">
        <button>
            <a href="{% url 'posts:t_update' tool.pk%}" style="color:black; text-decoration:none;">수정하기</a>
        </button>
        <button>
            <a href="{% url 'posts:t_list' %}" style="color:black; text-decoration:none;">목록</a>
        </button>
        <form action="{% url 'posts:t_delete' tool.pk%}" method="post">
            {% csrf_token %}
            <input type="submit" , value="삭제하기" />
        </form>
    </div>
</body>

</html>

SWIDEA_SITE/server/apps/posts/templates/posts/t_list.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>개발툴 관리 페이지</title>
    <link rel="stylesheet" href="{% static 'css/t_list.css'%}" />
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header><!-- 네비게이션바 -->
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:t_list' %}">My SW Idae Manage</a>
                <a class="nav-link active text-black small" href="{%url 'posts:create' %}">아이디어 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:list' %}">아이디어 관리</a>
                <a class="nav-link active text-black small" href="{%url 'posts:t_create' %}">개발 툴 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:t_list' %}">개발 툴 관리</a>
            </div>
        </nav>
    </header>

    <div class="title-box">
        <h1 class="title">DevTool List</h1>
        개발툴 목록 페이지 입니다. 자신이 사용가능한 개발들의 목록을 확인해 보세요.
    </div>

    {% if tool_list%}
    <section class="tool-list">
        {% for tool in tool_list %}
        <article>
            <p><a href="{% url 'posts:t_detail' tool.pk%}">{{tool.name}}</a></p>
            <div class="kind">{{tool.kind}}</div>
            <div class="content">{{tool.content}}</div>


        </article>
        <hr />
        {% endfor %}
    </section>
    {% endif %}

</body>

</html>

SWIDEA_SITE/server/apps/posts/templates/posts/t_update.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>개발툴 수정 페이지</title>
    <link rel="stylesheet" href="{% static 'css/update.css'%}" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header><!-- 네비게이션바 -->
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:list' %}">My SW Idae Manage</a>
                <a class="nav-link active text-black small" href="{%url 'posts:create' %}">아이디어 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:list' %}">아이디어 관리</a>
                <a class="nav-link active text-black small" href="{%url 'posts:t_create' %}">개발 툴 등록</a>
                <a class="nav-link active text-black small" href="{% url 'posts:t_list' %}">개발 툴 관리</a>
            </div>
        </nav>
    </header>

    <div class="title-box">
        <h1 class="title">DevTool Detail Update</h1>
        개발툴 세부내용 수정 페이지입니다. 개발툴에 대해 수정사항이 있으면 고쳐보아요.
    </div>

    <form action="{% url 'posts:t_update' tool.pk%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        이름:
        <input name="name" placeholder="이름" value="{{tool.name}}" />
        <br />
        종류:
        <input name="kind" placeholder="종류" value="{{tool.kind}}" />
        <br />
        개발툴 설명:
        <textarea name="content" placeholder="개발툴 설명 내용">{{tool.content}}</textarea>
        <br />
        <div>
            <input type="submit" , value="SUBMIT" />
        </div>
    </form>

</body>

</html>